version: "3.7"

services:
  helloChatDb:
    image: mongo:4.2.3-bionic
    container_name: helloChatDb-mongodb
    ports:
      - 27020:27017
    environment:
      - MONGO_INITDB_DATABASE=helloChat
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./db-data/mongo-data/:/var/lib/mongo/data/

  redis:
    image: redis
    container_name: helloChat_redis
    hostname: redis
    restart: on-failure
    expose:
      - 6382
    ports:
      - "6382:6379"

networks:
  socailbook_net:
    external:
      name: helloChat_net
